# Generated by Django 5.0.4 on 2024-04-30 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BookListAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'managed': True},
        ),
    ]
